version: '3.7'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./collector-config.yml:/otel-config.yaml
    command:
      - --config=/otel-config.yaml
    ports:
      - "4371:4317"  # OTLP gRPC
      - "4381:4318"  # OTLP HTTP
      - "55680:55680" # Legacy OTLP gRPC (optional)
#    depends_on:
#      - jaeger
#
#  jaeger:
#    image: jaegertracing/all-in-one:1.22
#    ports:
#      - "5775:5775/udp"    # UDP port for receiving traces
#      - "6831:6831/udp"    # UDP port for receiving traces from agent
#      - "6832:6832/udp"    # UDP port for receiving traces
#      - "16686:16686"      # Jaeger UI
#      - "14268:14268"      # Jaeger HTTP collector
#      - "14250:14250"      # Jaeger gRPC collector
#      - "9411:9411"        # Zipkin compatible endpoint

  # Optional: Python service could also be part of Docker Compose, but it is assumed to run locally in this example.
