version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics_prometheus_simplified.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

