{
 "title": "HotROD - Metrics and Logs Overview",
 "tags": [
  "Loki",
  "logging",
  "prometheus",
  "metrics",
  "jaeger",
  "hotrod"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "loki_query",
    "label": "Service",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" },
   {
    "name": "endpoint",
    "label": "Service",
    "query": {
     "query": "label_values(hotrod_requests_total,endpoint)"
    }
   },
   { "name": "container_name", "query": "hotrod" }
  ]
 },
 "panels": [
  {
   "title": "Loki Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"${container_name}\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of pattern $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of pattern: $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"${container_name}\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{job=\"${container_name}\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Percentage of \"$searchable_pattern\"  for specified time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"${container_name}\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({job=\"${container_name}\"})[$__interval]))",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Endpoint: $endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "endpoint",
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend HTTP response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hotrod_http_requests_total{endpoint=~\"$endpoint\"}[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Frontend requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(hotrod_http_requests_total{endpoint=\"/\"}[5m])) by (error)",
     "legendFormat": "{{endpoint}} error: {{error}}"
    }
   ]
  },
  {
   "title": "Frontend latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_request_latency_bucket{endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hotrod_request_latency_bucket{endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_request_latency_bucket{endpoint=\"/\"}[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}