receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: "hotrod"  # Replace with your service name
          static_configs:
            - targets: ['hotrod:8080']  # HotROD app's metrics endpoint

  filelog:
    include: [/var/lib/docker/containers/c654654a26fda0d0ec5226c9fcf93b2b06af48afd5a5166bf2b5c9388cca1518/*.log]
    start_at: end

exporters:
  otlp:
    endpoint: "jaeger:4317"  # Pointing to Jaeger for exporting traces
    tls:
      insecure: true
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:8889"  # Expose Prometheus metrics    
  otlphttp:
    endpoint: "loki:3100/otlp"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
    logs:
      receivers: [filelog]
      exporters: [loki]
