global:
  scrape_interval:     10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'    
    static_configs:
         - targets:
           - localhost:9090

  # - job_name: 'hotrod-application'
  #   static_configs:
  #        - targets:
  #          - hotrod:8080

  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets:
        - loki:3100
        
  - job_name: 'otel-collector'    
    static_configs:
         - targets:
           - otel-collector:8889
         