receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  jaeger:
    endpoint: "http://jaeger:14268/api/traces"
    insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [jaeger]
    traces:
      receivers: [otlp]
      exporters: [jaeger