global:
  scrape_interval: 5s  # Scrape targets every 5 seconds

scrape_configs:
  - job_name: 'prometheus-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.123.119.147:8000']  # Assuming you're running the Python app locally outside Docker
