version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.31
    container_name: jaeger_mixed_scenario
    ports:
      - "5775:5775/udp"       # For receiving traces from clients
      - "6831:6831/udp"       # For sending traces over UDP to the collector
      - "6832:6832/udp"       # For additional collector-to-collector communications
      - "5778:5778"           # For service UI to access internal Jaeger metrics
      - "16686:16686"         # Jaeger UI to view traces
      - "14268:14268"         # Jaeger's HTTP API for trace submissions
      - "14250:14250"         # Jaeger's gRPC collector API
      - "9411:9411"           # Zipkin-compatible trace endpoint (optional)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_mixed_scenario
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"           # Prometheus UI to view metrics and configurations

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

volumes:
  prometheus-data:
